meta_product_name: "Vivaio Millefoglie"
meta_title: "Millefoglie - Piante e Giardini"
meta_description: "Millefoglie è un giardino!
Ci sono un vivaio di piante erbacee perenni, graminacee ornamentali e annuali da fiore.
Un orto dei fiori in cui coltiviamo fiori da taglio.
Tante piante da vedere tra cui passeggiare... per scoprirle, conoscerle, portarle a casa.

Cerchiamo continuamente piante che ancora non conosciamo, nuove specie e varietà.

Scegliamo quelle più rustiche, poco esigenti e resistenti a parassiti e malattie; le sperimentiamo nel nostro giardino; le riproduciamo, coltiviamo e le offriamo a chi le apprezza.

Effettuiamo la vendita delle piante e dei fiori in vivaio o per corrispondenza.

Progettiamo e realizziamo giardini e terrazzi."
meta_image: "site-preview.jpg" # should exist in `app/assets/images/`
